"""
Centralized constants for the AutoGrade application.
"""

# Grading Constants
FUZZY_MATCH_THRESHOLD = 0.85
GRADE_A = 90.0
GRADE_B = 80.0
GRADE_C = 70.0
GRADE_D = 60.0

# HTTP Client Defaults
MAX_RETRIES = 3
DEFAULT_TIMEOUT_CONNECT_SECONDS = 5
DEFAULT_TIMEOUT_READ_SECONDS = 30
MAX_HTTP_CONNECTIONS = 100
MAX_KEEPALIVE_CONNECTIONS = 20

# AI/LLM Defaults
GEMINI_DEFAULT_FEEDBACK_CONFIDENCE = 0.0
